from app.models.user_profile import UserProfile
from app.models.metro_line import MetroLine
from app.models.station import Station
from app.models.line_station import LineStation
from app.models.journey import Journey
from app.models.train import Train
from app.models.train_schedule import TrainSchedule
from app.models.train_location import TrainLocation
from app.models.crowd_log import CrowdLog
from app.models.prediction import Prediction
from app.models.alert import Alert
from app.models.ai_model import AIModel
from app.models.notification_log import NotificationLog
