
"use client";

import { useEffect, useRef, useState } from "react";
import {
  BrainCircuit,
  TrendingUp,
  Lightbulb,
  TriangleAlert,
  CheckCircle2,
} from "lucide-react";

import { useStations } from "@/hooks/useStations";
import { getCrowdDashboard } from "@/lib/api/crowd";
import { getRecommendationsBulk } from "@/lib/api/predictions";
import { useSelectedState } from "@/providers/StateProvider";
import type { SmartRecommendation, Station } from "@/lib/api/types";

interface StationInsight extends SmartRecommendation {
  stationName: string;
}

const MAX_STATIONS_ANALYZED = 15;

// Phase 1 (P0-1) fix: this panel used to recompute on every single
// `crowd_update`/`delay_alert`/`station_alert` WebSocket event, which
// (with the simulator's default tick rate) fired roughly once every
// 10s and, on every firing, launched up to MAX_STATIONS_ANALYZED=15
// parallel recommendation requests - a request storm that blew past
// the backend's 20/minute rate limit and wrote duplicate DB rows on
// every "refresh". A live push event here means "something changed,
// maybe refetch on a schedule" - not "go recompute everything right
// now" - so this panel now refreshes on a fixed interval instead of
// reacting to the socket at all, exactly like the already-correct
// KPISection.tsx (LIVE_POLL_INTERVAL_MS) does for its own data.
const REFRESH_INTERVAL_MS = 45000;

export default function AIInsights() {
  const { selectedState } = useSelectedState();
  const { data: stations, loading: stationsLoading } = useStations();

  const [insights, setInsights] = useState<StationInsight[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshTick, setRefreshTick] = useState(0);

  // Guards against a fetch overlapping the previous one - e.g. if a
  // request is unusually slow and the next interval tick fires before
  // it resolves, that tick is skipped rather than stacking another
  // in-flight batch on top of it.
  const inFlightRef = useRef(false);

  useEffect(() => {
    const interval = setInterval(() => {
      if (inFlightRef.current) return;
      setRefreshTick((t) => t + 1);
    }, REFRESH_INTERVAL_MS);
    return () => clearInterval(interval);
  }, []);

  useEffect(() => {
    if (!stations || stations.length === 0) return;

    const controller = new AbortController();

    inFlightRef.current = true;
    setLoading(true);

    const stationsByName = new Map<number, Station>(
      stations.map((s) => [s.id, s]),
    );

    getCrowdDashboard(selectedState ?? undefined, controller.signal)
      .then((crowd) => {

        const rankedStationIds = [...crowd]
          .sort((a, b) => b.occupancy_ratio - a.occupancy_ratio)
          .slice(0, MAX_STATIONS_ANALYZED)
          .map((c) => c.station_id);

        const targetIds = rankedStationIds.length > 0
          ? rankedStationIds
          : stations.slice(0, MAX_STATIONS_ANALYZED).map((s) => s.id);

        // Single bulk call instead of one request per station - see
        // getRecommendationsBulk()/the backend's
        // smart_recommendations_bulk() for the full rationale.
        return getRecommendationsBulk(targetIds, controller.signal).then(
          (recsByStation) =>
            targetIds.flatMap((stationId) =>
              (recsByStation.get(stationId) ?? []).map((rec) => ({
                ...rec,
                stationName: stationsByName.get(stationId)?.station_name ?? "",
              })),
            ),
        );
      })
      .then((flat) => {
        // Show the more urgent (warning) items first.
        const sorted = [...flat].sort((a, b) =>
          a.severity === b.severity ? 0 : a.severity === "warning" ? -1 : 1,
        );
        setInsights(sorted.slice(0, 6));
        setLoading(false);
      })
      .catch(() => {
        if (controller.signal.aborted) return;
        setLoading(false);
      })
      .finally(() => {
        if (!controller.signal.aborted) {
          inFlightRef.current = false;
        }
      });

    return () => {
      controller.abort();
      inFlightRef.current = false;
    };
  }, [stations, selectedState, refreshTick]);

  const isLoading = stationsLoading || loading;
  const warningCount = insights.filter((i) => i.severity === "warning").length;

  return (
    <section className="rounded-3xl border border-border bg-card p-8">

      <div className="mb-8 flex items-center justify-between">

        <div>

          <h2 className="text-2xl font-bold">
            AI Insights
          </h2>

          <p className="mt-2 text-muted">
            Real-time recommendations generated by AI
          </p>

        </div>

        <div
          className="
          flex
          h-14
          w-14
          items-center
          justify-center
          rounded-2xl
          bg-primary/10
          "
        >
          <BrainCircuit
            className="text-primary"
            size={30}
          />
        </div>

      </div>

      {isLoading ? (
        <p className="text-sm text-muted">Generating AI insights...</p>
      ) : (
      <div className="space-y-5">

        {insights.map((item, index) => (

          <div
            key={`${item.station_id}-${index}`}
            className="
            rounded-2xl
            border
            border-border
            p-5
            transition
            duration-300
            hover:border-primary
            hover:shadow-lg
            "
          >

            <div className="flex justify-between">

              <div>

                <h3 className="font-semibold text-lg">
                  {item.stationName || item.title}
                </h3>

                <p className="mt-3 text-sm text-muted leading-7">
                  {item.detail}
                </p>

              </div>

              <div>

                {item.severity === "warning" ? (
                  <TrendingUp
                    className="text-orange-500"
                    size={24}
                  />
                ) : (
                  <CheckCircle2
                    className="text-green-500"
                    size={24}
                  />
                )}

              </div>

            </div>

            <div className="mt-6 flex items-center justify-between">

              <div className="flex items-center gap-2">

                <Lightbulb
                  className="text-yellow-500"
                  size={18}
                />

                <span className="text-sm text-muted">
                  {item.title}
                </span>

              </div>

              <span
                className={`
                rounded-full
                px-4
                py-2
                text-xs
                font-semibold

                ${
                  item.severity === "warning"
                    ? "bg-orange-500/10 text-orange-500"
                    : "bg-green-500/10 text-green-500"
                }
                `}
              >
                {item.severity.toUpperCase()}
              </span>

            </div>

          </div>

        ))}

        {insights.length === 0 && (
          <p className="text-sm text-muted">No AI insights available right now.</p>
        )}

      </div>
      )}

      <div
        className="
        mt-8
        rounded-2xl
        border
        border-blue-500/20
        bg-blue-500/5
        p-6
        "
      >

        <div className="flex items-start gap-4">

          <TriangleAlert
            className="mt-1 text-blue-500"
            size={24}
          />

          <div>

            <h4 className="font-bold">
              AI Summary
            </h4>

            <p className="mt-2 text-muted leading-7">
              {warningCount > 0
                ? `MetroFlow AI flagged ${warningCount} station${warningCount === 1 ? "" : "s"} needing attention right now - see the warnings above for crowd and delay risk detail.`
                : "MetroFlow AI has no active warnings - all monitored stations are within normal operating range."}
            </p>

          </div>

        </div>

      </div>

    </section>
  );
}
