
export const queryKeys = {
  stations: "stations",
  trains: "trains",
  liveTrainPositions: "live-train-positions",
  upcomingSchedules: "upcoming-schedules",
  schedules: "schedules",
  delayedSchedules: "delayed-schedules",
  activeJourney: "active-journey",
  crowdDashboard: "crowd-dashboard",
  crowdHeatmap: "crowd-heatmap",
  crowdModelMetrics: "crowd-model-metrics",
  delayModelMetrics: "delay-model-metrics",
  frequencyModelMetrics: "frequency-model-metrics",
  stationMonitor: "station-monitor",
  stationAnalytics: "station-analytics",
  inflowOutflow: "inflow-outflow",
  passengerFlowOverview: "passenger-flow-overview",
  trafficPattern: "traffic-pattern-aggregate",
  predictionInsights: "prediction-insights",
  alerts: "alerts",
  enquiries: "enquiries",
  enquiryStats: "enquiry-stats",
  news: "news",
  notifications: "notifications",
  notificationsUnreadCount: "notifications-unread-count",
  users: "users",
  systemLogs: "system-logs",
  systemStatus: "system-status",
  trafficReport: "traffic-report",
  operationalSummary: "operational-summary",
} as const;